"""empty message

Revision ID: 826bc8e86b58
Revises: 
Create Date: 2020-08-06 13:22:28.625364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826bc8e86b58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doktori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=120), nullable=True),
    sa.Column('prezime', sa.String(length=120), nullable=True),
    sa.Column('specijalizacija', sa.String(length=120), nullable=True),
    sa.Column('bolnica', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('ocjena',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocjena', sa.Integer(), nullable=True),
    sa.Column('komentar', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('doktor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doktor_id'], ['doktori.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocjena')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('doktori')
    # ### end Alembic commands ###
