"""empty message

Revision ID: cf8d2d64752c
Revises: 54c633812ce8
Create Date: 2020-08-28 22:27:35.883977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8d2d64752c'
down_revision = '54c633812ce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clanak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naslov', sa.String(length=120), nullable=True),
    sa.Column('opis', sa.String(length=1000), nullable=True),
    sa.Column('link', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clanak')
    # ### end Alembic commands ###
